services:
  # 1. PHP Application
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sae-bakery-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./storage:/var/www/storage
      - ./bootstrap/cache:/var/www/bootstrap/cache
      - build_assets:/var/www/public/build
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
    networks:
      - jaringan-pusat # <--- Gabung ke jaringan pusat

  # 2. Nginx Web Server
  web:
    image: nginx:alpine
    container_name: sae-bakery-web
    restart: unless-stopped
    ports:
      - "8000:80" # <--- Ganti ke 8000 (karena 8080 dipakai phpMyAdmin)
    volumes:
      - ./:/var/www
      - ./docker/nginx/conf.d:/etc/nginx/conf.d:ro
      - build_assets:/var/www/public/build
    networks:
      - jaringan-pusat # <--- Gabung ke jaringan pusat
    depends_on:
      - app

# Service 'db' KITA HAPUS karena pakai Master-DB

volumes:
  build_assets:
    driver: local

networks:
  # Kita panggil jaringan luar yang sudah kita buat
  jaringan-pusat:
    external: true
